name: 'Test and verify build'

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-api:
    name: 'Run mvn verify'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: 'Run maven tests'
        run: mvn -f ./api/pom.xml -B verify

  test-web-app:
    name: 'Run npm tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Setup node'
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'web-app/package-lock.json'

      - name: 'Install dependencies'
        run: npm ci --legacy-peer-deps --prefix web-app

      - name: 'Run tests'
        run: npm run test --prefix web-app
